version: '1'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:6000"
    command: ["gunicorn", "--reload", "-b", "0.0.0.0:6000", "app:app"]
    volumes:
      - ../app:/app
