version: '1'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:5000"
    command: ["gunicorn", "--reload", "-b", "0.0.0.0:5000", "app:app"]
    volumes:
      - ../app:/app
